### ISSUE TITLE
CoordArray wrongly tagged as AMD

### ISSUE THREAD

**Issue by gratex** [vvoovv/djeo-gmaps#1]
All '.js' files are tagged as AMD in profile (djeo-gmaps.profile.js). 

But this is not true, 'djeo-gmaps/CoordArray.js' does not have AMD syntax, 
which causes an error in Dojo build.

```
error(307) Failed to evaluate module tagged as pure AMD (fell back to processing with regular expressions).
```

This file should be rewritten to AMD syntax, or profile should be updated not to mark it as AMD.

**Comment by vvoovv** [comment]
I haven't used that module. Could you provide a fix?

**Comment by gratex** [comment]
I would provide a fix (pull request), but I need to know the purpose of this module.
Because I haven't found any usage in other modules, and it is also not mentioned in documentation. 

Rewriting the module to AMD would not be a problem, except the line which relies on global 'google' object, which may not exist in time when factory function is executed.

I would suggest to add 'init' method, same as in Placemark.js

```
Placemark.init = function() {
    GM = google.maps;
};
```

But as long as I do not know how is this module used (or if is it even used), I cannot do it, because it could break the backward compatibility.

I hoped that you as the author would know.

**Comment by vvoovv** [comment]
This module was created to support editing of LineStrings:
push(..) adds a point to a LineString
set(..) inserts a point to a LineString

I haven't used that module for years, that's why it wasn't converted to AMD.

**Comment by gratex** [comment]
Since I still don't know how CoordArray should be used, or how people usually use it (or whether anyone uses it at all), I can't make the trick with CoordArray.init, without breaking the backward compatibility. 

So the best solution seems to be just not tag the module as AMD.
